import * as fs from 'fs';

let fileContent = fs.readFileSync('src/App.tsx', 'utf-8');

// The exact string block from line 81 to 142
const oldBlock = `  // --- 2. 내분비·면역계 약물 (MFDS 2025) ---
  {
    id: '2-1',
    category: '내분비',
    name: '인슐린 (Insulin)',
    pregnancySafety: 'safe',
    pregnancyNote: '임신성 당뇨 표준 치료. 태반 통과 안 함.',
    lactationSafety: 'safe',
    lactationNote: '수유 중 안전.',
    brands: '휴물린 등',
  },
  {
    id: '2-2',
    category: '내분비',
    name: '메트포르민 (Metformin)',
    pregnancySafety: 'caution',
    pregnancyNote: 'PCOS 또는 인슐린 내성 시 사용. 기형 위험 증거 부족하나 유익성 판단하에 사용.',
    lactationSafety: 'safe',
    lactationNote: '수유 중 안전.',
    brands: '다이아벡스 등',
  },
  {
    id: '2-3',
    category: '내분비',
    name: '프로필티오우라실 (Propylthiouracil / PTU)',
    pregnancySafety: 'safe',
    pregnancyNote: '임신 1분기 항갑상선제 1차 선택제.',
    lactationSafety: 'safe',
    lactationNote: '수유 중 안전.',
    brands: '안티로이드 등',
  },
  {
    id: '2-4',
    category: '내분비',
    name: '레보티록신 (Levothyroxine)',
    pregnancySafety: 'safe',
    pregnancyNote: '갑상선저하증 필수 치료제. 임신 중 요구량 증가로 증량 필요.',
    lactationSafety: 'safe',
    lactationNote: '수유 중 안전.',
    brands: '씬지로이드 등',
  },
  {
    id: '2-5',
    category: '내분비',
    name: '프레드니솔론 (Prednisolone)',
    pregnancySafety: 'safe',
    pregnancyNote: '국소/전신 모두 1분기 고용량만 주의(구순구개열 위험 소폭 상승).',
    lactationSafety: 'safe',
    lactationNote: '수유 중 안전.',
    brands: '소론도 등',
  },
  {
    id: '2-6',
    category: '내분비',
    name: '메토트렉세이트 (Methotrexate)',
    pregnancySafety: 'avoid',
    pregnancyNote: '절대 금기. 태아 사망 및 안면, 두개골 기형 유발.',
    lactationSafety: 'avoid',
    lactationNote: '수유 중 금기.',
    brands: '유한 MTX 등',
  },`;

const newBlock = `  // --- 2. 내분비 및 대사 질환 (MFDS 2025) ---
  // [당뇨병 치료제]
  {
    id: '2-1',
    category: '당뇨병',
    name: '인슐린 (Insulin)',
    pregnancySafety: 'safe',
    pregnancyNote: '배·태아 독성이나 기형 유발 작용이 없어 임신 중 가장 우선적으로 권고되는 1차 치료제입니다. 적극적인 투여로 혈당을 조절하는 것이 필수적입니다.',
    lactationSafety: 'safe',
    lactationNote: '수유 중 안전하게 사용 가능합니다.',
    brands: '휴물린, 란투스, 노보래피드',
  },
  {
    id: '2-2',
    category: '당뇨병',
    name: '메트포르민 (Metformin)',
    pregnancySafety: 'caution',
    pregnancyNote: '인슐린을 사용할 수 없는 경우에만 제한적으로 고려할 수 있으나, 태반을 통과하고 출생아 과체중 위험이 있어 우선 권장되지 않습니다.',
    lactationSafety: 'safe',
    lactationNote: '수유 중 비교적 안전합니다.',
    brands: '다이아벡스, 글루코파지',
  },
  {
    id: '2-3',
    category: '당뇨병',
    name: '글리벤클라마이드 (Glibenclamide)',
    pregnancySafety: 'caution',
    pregnancyNote: '태반을 통과하며 과체중아 및 신생아 저혈당 발생 위험이 메트포르민이나 인슐린보다 열등하여 추천되지 않습니다.',
    lactationSafety: 'caution',
    lactationNote: '수유 중 영아 저혈당 모니터링이 필요합니다.',
    brands: '유글루콘 정',
  },
  {
    id: '2-4',
    category: '당뇨병',
    name: 'GLP-1 작용제 (-glutide)',
    pregnancySafety: 'avoid',
    pregnancyNote: '❌ 절대 금기. 임부 사용 데이터가 없거나 동물실험 독성이 있어 복용 중 피임이 필수이며 임신 전 반드시 중단해야 합니다.',
    lactationSafety: 'avoid',
    lactationNote: '수유 중 안전성 미확립으로 금기입니다.',
    brands: '삭센다, 위고비, 트루리시티',
  },
  {
    id: '2-5',
    category: '당뇨병',
    name: 'SGLT-2 억제제 계열 (Gliflozins / Flozins)',
    pregnancySafety: 'avoid',
    pregnancyNote: '❌ 절대 금기. 생식 및 신장 독성 우려가 있어 복용 중 피임이 필수이며 임신 전 반드시 중단해야 합니다.',
    lactationSafety: 'avoid',
    lactationNote: '수유 중 신장 발달 위험으로 금기입니다.',
    brands: '포시가, 자디앙, 슈글렛',
  },
  {
    id: '2-6',
    category: '당뇨병',
    name: 'DPP-4 억제제 (-gliptin)',
    pregnancySafety: 'avoid',
    pregnancyNote: '❌ 절대 금기. 동물실험 독성 등으로 인해 복용 중 피임이 필수이며 임신 전 반드시 중단해야 합니다.',
    lactationSafety: 'avoid',
    lactationNote: '수유 중 금기입니다.',
    brands: '자누비아, 트라젠타, 가브스',
  },

  // [이상지질혈증 치료제]
  {
    id: '2-7',
    category: '이상지질혈증',
    name: '오메가-3 보충제 (DHA)',
    pregnancySafety: 'safe',
    pregnancyNote: '콜레스테롤 조절보다는 태아 뇌 발달을 위해 일일 최소 200~300mg 섭취가 권장됩니다.',
    lactationSafety: 'safe',
    lactationNote: '수유 중 안전합니다.',
    brands: '오메가-3 건강기능식품 및 의약품류',
  },
  {
    id: '2-8',
    category: '이상지질혈증',
    name: '스타틴 계열 (Simvastatin / Atorvastatin / Pitavastatin / Rosuvastatin / Pravastatin)',
    pregnancySafety: 'avoid',
    pregnancyNote: '❌ 절대 금기. 콜레스테롤은 태아 발달에 필수적이므로 계획 임신 최소 6~12주 전 중단이 필수입니다.',
    lactationSafety: 'avoid',
    lactationNote: '수유 중 사용 금기입니다.',
    brands: '리피토, 크레스토, 조코',
  },
  {
    id: '2-9',
    category: '이상지질혈증',
    name: '피브레이트 계열 (Bezafibrate / Fenofibrate)',
    pregnancySafety: 'avoid',
    pregnancyNote: '❌ 절대 금기. 동물실험에서 제3삼분기 태아 축적 위험이 관찰되어 임신 중 금기입니다.',
    lactationSafety: 'avoid',
    lactationNote: '수유 중 금기입니다.',
    brands: '리피딜수프라, 베잘립',
  },
  {
    id: '2-10',
    category: '이상지질혈증',
    name: '기타 지질저하제 (Ezetimibe / Nicotinic acid / Acipimox)',
    pregnancySafety: 'avoid',
    pregnancyNote: '❌ 절대 금기. 임부 안전성 데이터 부족 및 기형 발생 우려로 임신 중 투약을 금지합니다.',
    lactationSafety: 'avoid',
    lactationNote: '수유 중 금기입니다.',
    brands: '이지트롤, 니아스파',
  },

  // [갑상선 질환 치료제]
  {
    id: '2-11',
    category: '갑상선',
    name: '레보티록신 (Levothyroxine)',
    pregnancySafety: 'safe',
    pregnancyNote: '태반을 쉽게 통과하지 않으며 부작용이 없어 가장 안전하게 신속히 투여해야 하는 호르몬제입니다. 임신 시 증량이 필요할 수 있습니다.',
    lactationSafety: 'safe',
    lactationNote: '수유 중 매우 안전합니다.',
    brands: '씬지로이드, 씬지록신',
  },
  {
    id: '2-12',
    category: '갑상선',
    name: '리오티로닌 및 건조 갑상선 제제 (Liothyronine / Desiccated Thyroid)',
    pregnancySafety: 'avoid',
    pregnancyNote: '❌ 사용 금지. T3 제제 및 동물 유래 갑상선 제제는 임신 중 생리적 변동이 크고 제어하기 어려워 사용이 금지됩니다.',
    lactationSafety: 'avoid',
    lactationNote: '수유 중 권장되지 않습니다.',
    brands: '테트로닌, 아머타이로이드',
  },
  {
    id: '2-13',
    category: '갑상선',
    name: '프로필티오우라실 (Propylthiouracil)',
    pregnancySafety: 'caution',
    pregnancyNote: '메티마졸보다 기형 빈도와 중증도가 낮아 임신 1삼분기(초기) 항갑상선제 치료 시 우선 권고됩니다. 간독성에 주의하십시오.',
    lactationSafety: 'safe',
    lactationNote: '수유 중 소량 투여 가능합니다.',
    brands: '안티로이드 정',
  },
  {
    id: '2-14',
    category: '갑상선',
    name: '메티마졸 (Methimazole)',
    pregnancySafety: 'caution',
    pregnancyNote: '피부 무형성증, 식도/후비공 폐쇄 등 메티마졸 배아병증 유발 가능성이 있어 1삼분기에는 회피하고, 2삼분기 이후 제한적으로 전환 고려할 수 있습니다.',
    lactationSafety: 'safe',
    lactationNote: '수유 중 최대 20mg까지 비교적 안전합니다.',
    brands: '메티마졸 정',
  },`;

fileContent = fileContent.replace(oldBlock, newBlock);

fs.writeFileSync('src/App.tsx', fileContent);
console.log('Successfully completed literal string replacement of Endocrine data.');
